### ISSUE TITLE
Cannot download apk from china

### ISSUE THREAD

**Issue by srghma** [ProtonVPN/android-app#111]
https://protonvpn.com/download-android

Is blocked

How to download?

**Comment by zynoxz** [comment]
Use proxies

**Comment by mateusz-markowicz** [comment]
Hello Serhii, there are of alternative sources that users can try:
- github (https://github.com/ProtonVPN/android-app/releases) - preferred
- https://f-droid.org/en/packages/ch.protonvpn.android/
but if they are blocked, they'd need to get the apk delivered on their own. Also note that ProtonVPN will not necessarily work reliably in China, even with Stealth protocol, due to the sophistication of their Great Firewall.
