### ISSUE TITLE
New signature

### ISSUE THREAD

**Issue by Blend0963** [ProtonVPN/android-app#143]
The latest version (5.5.68.0) does not have the correct signature, why ? Is this normal ?

**Comment by Gitchick57** [comment]
What does that mean for the users?



Aug 21, 2024, 5:33 PM by ***@***.***:

**Comment by Gitchick57** [comment]
Got it.  Thanks so much for your reply.



Aug 21, 2024, 6:15 PM by ***@***.***:

**Comment by BHydden** [comment]
Possibly has something to do with the latest release being published by @mateusz-markowicz instead of @proton-ci ?
Hopefully it was just accidentally signed with the wrong key and they can release a hotfix correcting it. 

Since it wasn't mentioned in the release notes, I'm guessing it wasn't intentional.

**Comment by AlgirdasPundzius** [comment]
Yes, this was a mistake on our side. We changed the release process, so most recent release was done manually and simply incorrect artifact which was signed with debug key was picked. 
We have fixed the 5.5.68.0 release now, so the apk should be good and signed with release key.
