### ISSUE TITLE
App bundle support

### ISSUE THREAD

**Issue by st0rmr1der1994** [ProtonVPN/android-app#3]
Hi guys. Do you have app bundle support for publishing? As I can see, your oVPN implementation is kinda based on https://github.com/schwabe/ics-openvpn. 

Here is a link to a workaround for making possible to execute ovpn lib from LD_LIBRARY_PATH on Android Q -> https://github.com/schwabe/ics-openvpn/issues/1003#issuecomment-501043423

However, this feature is experimental and may be broken or deprecated in future. Did you guys implement something relatable on your side?

PS. If you are using libandroidbridge.so and loading it with Relinker, have you ever encountered any crashes with com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary?

**Comment by AlgirdasPundzius** [comment]
Hello,
We didn't ran into any issues while using Relinker. It actually helped us to solve some issues which we were having earlier on when loading native libraries. 

As for app bundle we do not use it, nor do we plan to start using it. Mainly because that would mean we would need to hand over our signing key to google and we consider that as a security threat. To reduce .apk size we use abi splitting and while it may not be as good as google app bundle it is better than handing over our signing key to them.
