### ISSUE TITLE
Persistent Notification

### ISSUE THREAD

**Issue by heiserhorn** [ProtonVPN/android-app#43]
Hi,

I am running the F droid version (2.2.3) on a pixel 4 with stock Android 11 and there is a persistent notification with the status of the VPN connection (not connected or the details of the connection).

The only way to remove it is to turn notification from this app off (which is not ideal). Would it me possible to change the behavior of the notification and make it not persistent?

Happy to try the latest version but apparently it is failing to build on F droid. See latest build report as of 16 Oct https://f-droid.org/wiki/index.php?title=ch.protonvpn.android/lastbuild_102035400&direction=next&oldid=280441

Best regards

Mike

**Comment by mateusz-markowicz** [comment]
Hi, persistent notification is fixed in our internal repo and will be available at our next release. F-droid builds are unfortunately failing atm and preventing publish of the current version, we'll try to have it fixed as soon as possible. Current production build is also available here: https://github.com/ProtonVPN/android-app/releases/tag/2.3.54.0

**Comment by Ammako** [comment]
I have Status icon off, but I have a persistent notification anyway.
