### ISSUE TITLE
Make Swiss flag square

### ISSUE THREAD

**Issue by thgoebel** [ProtonVPN/android-app#57]
**Expected behaviour:**
The Swiss flag should be [square](https://en.wikipedia.org/wiki/Flag_of_Switzerland) (ProtonVPN is not [civil vessel](https://en.wikipedia.org/wiki/Civil_ensign#Civil_ensigns_differing_from_the_national_flag_in_the_proportions) afaik).

**Actual behaviour:**
The Swiss flag is a non-square rectangle, like all the other flags.

<img src=https://user-images.githubusercontent.com/33295590/109608487-40be7a80-7b2a-11eb-9154-acc2019213f4.png height=300>

**Comment by AlgirdasPundzius** [comment]
Thanks for the suggestion. For aesthetic consistency reasons we so far employed rectangular versions of all the flags, so that it simplify their handling across all of our devices (Windows, AndroidTV etc.) and let us focus our energy on the performance and quality of the VPN service. When we'll work on redesign of our apps we'll definitively consider the opportunity of representing the national flags in their respective shapes, if possible.
